name: Actions

on: push

jobs:
  cypress:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get .env file
        run: |
          echo "PGURI=${{ secrets.PASS }}" > .env
          echo "POSTGRES_PASSWORD=${{ secrets.PASSW }}" >> .env

      - name: Start frontend
        run: |
          cd frontend
          npm install
          npm run dev &
          sleep 5

      - name: Cypress run
        run: |
          cd frontend
          npm start
          npm run cy:run-unit
