name: Actions

on: push

jobs:
  cypress:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get .env file
        run: |
          echo ${{ secrets.PASS }} > .env
          echo ${{ secrets.PASSW }} >> .env

      - name: Start Docker
        run: docker-compose -f compose.yaml up -d

      - name: Start frontend
        run: |
          cd frontend
          npm install
          npm run dev &
          sleep 5

      - name: Cypress run
        run: |
          cd frontend
          npm start -p 3000
          npm run cy:run-unit
